### ISSUE TITLE
간단 코드 리뷰 

### ISSUE THREAD

**Issue by flynnpark** [hyeonheebee/assignment-final-react-js-design-#8]
안녕하세요, 허니비님! 
주말에 시간이 안 나서 이제서야 코드리뷰를 남겨봅니다. 부디 도움되는 리뷰를 남길 수 있길 바랍니다. 가볍게 봐주세요~~

### 컴포넌트 분리

허니비님 요즘 생활을 보아하니 시간이 부족해서 못하신 것 같아서 아쉬운 부분입니다. 공통 컴포넌트 부분의 분리가 아쉬워요. 영화 목록들의 데이터 모양은 똑같기 때문에, 어느 정도 컴포넌트의 공통화를 충분히 할 수 있을 것 같아요. 가령 아래와 같은 부분 말이에요.

```ts
{popularData?.results?.map((m) => (
  <Container
    whileHover={{ scale: 1.2, cursor: "pointer" }}
    key={m.id}
    variants={MovieListVariants}
  >
    <HeartDiv
      whileHover={{
        scale: 1.1,
        cursor: "pointer",
        color: ["grey", "tomato"],
      }}
    >
      <svg
        onClick={() => {
          setLike((pre) => [...pre, m.title]);
        }}
        fill="currentColor"
        viewBox="0 0 20 20"
        aria-hidden="true"
      >
        <path d="M9.653 16.915l-.005-.003-.019-.01a20.759 20.759 0 01-1.162-.682 22.045 22.045 0 01-2.582-1.9C4.045 12.733 2 10.352 2 7.5a4.5 4.5 0 018-2.828A4.5 4.5 0 0118 7.5c0 2.852-2.044 5.233-3.885 6.82a22.049 22.049 0 01-3.744 2.582l-.019.01-.005.003h-.002a.739.739 0 01-.69.001l-.002-.001z" />
      </svg>
    </HeartDiv>
    <Link to={`${m.id}`} onClick={() => handleClick(m.id)}>
      {m.title} <img src={makeImagePath(m.poster_path)} />{" "}
    </Link>
  </Container>
))}
```

요 부분은 모든 페이지에서 공통적으로 나오는 부분인데, 적당히 공통화를 할 수 있었을 것으로 보여요. 그리고 요 부분에서 `svg` 부분도 따로 아이콘 컴포넌트로 뺐으면 이 아이콘이 어떤 아이콘이겠구나~ 하고 조금 더 쉽게 알 수 있었을 것 같아요.

### 인라인 스타일과 스타일드 컴포넌트의 혼용

이것도... 뭔가 맘이 급하셨을 거라고 추측해요. 어떤 곳은 스타일드 컴포넌트를 잘 사용하셨는데, 어떤 부분은 인라인 스타일이 있어요. 이렇게 혼용하게 되면 나중에 유지보수하기 어려워요...!

### 조금 아쉬운 상수값 처리

이런 저런 컴포넌트들을 보다 보니 `NOTFOUND`라는 상수값이 눈에 들어와버렸어요... 상수값 파일을 따로 만들어서 관리했으면 나중에 이미지를 바꾸는 일이 생겼을 때 간단하게 대처할 수 있을 것 같아요. 다른 값들도 요런 게 있다면 잘~ 빼내서 공통화 & 상수화 해봅시다.

### 추가 기능

추가기능을 구현하려고 한 건 좋은데, 로직 공통화를 해서 관리했으면 어땠을까 싶고, 해당 기능을 제대로 구현하려 했으면 전역 상태 + LocalStorage 같은 걸 사용했으면 좀 더 좋았을 것 같아요! 하지만 시도는 좋았다! 그만큼 다르게 해볼 방법도 많다! 

### 어쨌든 완성했다

여러 아쉬운 점이 있지만 중요한 건 주어진 과제를 완성시키는 것이라고 생각해요. 그런 점에서 요구사항 만족하면서 완성시킨 건 넘 잘하셨습니다...! 그러니까 10주 스터디 완주까지 화이팅입니다!!!! 고생 많으셨어요.

**Comment by hyeonheebee** [comment]
제가 느끼는 점을 같이 많이 짚어주셔서 정말 공감가는 코드리뷰였습니다! 
컴포넌트화나 반복을 없애는부분 , 가독성이 떨어지는 부분, 통일성에 대한 부분을 좀 더 리팩토링 해보겠습니다 :) 
NotFound 이미지도 따로 빼는 옵션을 생각못해봤는데, 그게 훨씬 좋았을것같네요 ! 
역시 구현뿐만이 아니라 유지보수나 추후 공유상황에도 좋은 코드가 되기위해 더 많이 고민하겠습니다 
아무래도 저 역시 작성하면서.. 흠 아쉽고 너무 반복이 많은데..싶은 부분이 많았던 프로젝트였어요 
추가기능도 구현을 시도해본 만큼 역시 localStorage 로 진짜 todolist구현하듯 기능을 좀 더 디벨롭 해보겠습니다 :) 
바쁜시간에도 코드리뷰 너무 감사합니다!! 포기하지 않고 keep going..! :)
